#include <../src/feti/einsfeti2.h>
#include <private/einsvecimpl.h>
#include <petsc/private/matimpl.h>
#include <einsksp.h>
#include <einssys.h>
#include <einspc.h>


#if defined(HAVE_SLEPC)


#undef __FUNCT__
#define __FUNCT__ "FETI2ComputeMatrixG_GENEO"
/*@
   FETI2ComputeMatrixG_GENEO - Computes GENEO modes.

   Input Parameters:
.  ft - the FETI context

@*/
PetscErrorCode FETI2ComputeMatrixG_GENEO(FETI ft)
{
  PetscErrorCode ierr;
  PC             pc;
  PCType         pctype;
  PetscBool      flg;
  
  PetscFunctionBegin;
  ierr = KSPGetPC(ft->ksp_interface,&pc);CHKERRQ(ierr);
  ierr = PCGetType(pc,&pctype);CHKERRQ(ierr);
  ierr = PetscStrcmp(PCFETI_DIRICHLET,pctype,&flg);CHKERRQ(ierr);
  /* if (flg) { */
    
  /* } */
  
  PetscFunctionReturn(0);
}


#undef __FUNCT__
#define __FUNCT__ "FETISetUp_FETI2_GENEO"
/*@
   FETISetUp_FETI2_GENEO - Setups structures need for FETI2 GENEO.

   Input Parameters:
.  ft - the FETI context

@*/
PetscErrorCode FETISetUp_FETI2_GENEO(FETI ft)
{
  PetscErrorCode ierr;
  FETI_2         *ft2 = (FETI_2*)ft->data;
  PC             pc;
  PCType         pctype;
  PetscBool      flg;
  GENEO_C        *gn;
  
  PetscFunctionBegin;
  ierr       = PetscNewLog(ft,&gn);CHKERRQ(ierr);
  ft2->geneo = gn;
  
  ierr = KSPGetPC(ft->ksp_interface,&pc);CHKERRQ(ierr);
  ierr = PCGetType(pc,&pctype);CHKERRQ(ierr);
  ierr = PetscStrcmp(PCFETI_DIRICHLET,pctype,&flg);CHKERRQ(ierr);
  /* if (flg) { */
    
  /* } */
  
  PetscFunctionReturn(0);
}


#undef __FUNCT__
#define __FUNCT__ "FETIDestroy_FETI2_GENEO"
/*@
   FETIDestroy_FETI2_GENEO - Destroys structures generated by FETI2 with GENEO modes.

   Input Parameters:
.  ft - the FETI context

@*/
PetscErrorCode FETIDestroy_FETI2_GENEO(FETI ft)
{
  PetscErrorCode ierr;
  FETI_2         *ft2 = (FETI_2*)ft->data;
  GENEO_C        *gn  = ft2->geneo;
  
  PetscFunctionBegin;
  ierr = PetscFree(ft2->geneo);CHKERRQ(ierr);
  PetscFunctionReturn(0);
}


#endif
